const state={sample:'digit',image:null,reviewed:false,queue:3};
const samples={digit:{prediction:'Seven',confidence:.99,familiarity:.99,uncertainty:.01,quality:.99,risk:.01},object:{prediction:'Unknown object',confidence:.71,familiarity:.63,uncertainty:.34,quality:.82,risk:.12},noise:{prediction:'Unrecognized pattern',confidence:.28,familiarity:.09,uncertainty:.86,quality:.31,risk:.28}};
const $=id=>document.getElementById(id);
const clamp=value=>Math.max(0,Math.min(1,value));
function setBar(id,value){$(id).style.width=`${Math.round(clamp(value)*100)}%`}
function showToast(message){$('toast').querySelector('span').textContent=message;$('toast').classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function drawSample(type){const canvas=$('preview-canvas'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,440,260);ctx.fillStyle=type==='noise'?'#303a31':'#e8eedf';ctx.fillRect(0,0,440,260);if(type==='digit'){ctx.strokeStyle='#26352b';ctx.lineWidth=18;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(220,70);ctx.quadraticCurveTo(280,34,300,80);ctx.quadraticCurveTo(300,125,200,214);ctx.stroke();ctx.beginPath();ctx.moveTo(197,214);ctx.quadraticCurveTo(290,214,326,214);ctx.stroke()}else if(type==='object'){ctx.fillStyle='#80a451';ctx.beginPath();ctx.arc(220,130,72,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f6f7f2';ctx.beginPath();ctx.arc(194,116,9,0,Math.PI*2);ctx.arc(246,116,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#26352b';ctx.beginPath();ctx.arc(194,116,4,0,Math.PI*2);ctx.arc(246,116,4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#26352b';ctx.lineWidth=7;ctx.beginPath();ctx.arc(220,126,33,0.2,Math.PI-.2);ctx.stroke()}else{for(let i=0;i<900;i++){ctx.fillStyle=`hsl(${Math.random()*100+80},${30+Math.random()*50}%,${25+Math.random()*55}%)`;ctx.fillRect(Math.random()*440,Math.random()*260,Math.random()*8,Math.random()*8)}}}
function analyze(){const data=samples[state.sample];const ars=clamp((.3*data.confidence+.3*data.familiarity+.2*data.quality-.2*data.uncertainty)*(1-data.risk));const decision=ars>=.75?'ACT':ars>=.4?'REVIEW':'STOP';state.reviewed=false;$('ars-value').textContent=ars.toFixed(2);$('decision-title').textContent=decision;$('prediction-value').textContent=data.prediction;$('prediction-confidence').textContent=`${Math.round(data.confidence*100)}% confidence`;['confidence','familiarity','uncertainty','quality'].forEach(key=>{$(`${key}-value`).textContent=data[key].toFixed(2);setBar(`${key}-bar`,data[key])});$('decision-marker').style.left=`${Math.round(ars*100)}%`;$('score-circle').style.borderColor=decision==='ACT'?'#86a94f':decision==='REVIEW'?'#d4a94d':'#dc8062';$('formula-result').textContent=`= [${(.3*data.confidence).toFixed(3)} + ${(.3*data.familiarity).toFixed(3)} + ${(.2*data.quality).toFixed(3)} - ${(.2*data.uncertainty).toFixed(3)}] x ${(1-data.risk).toFixed(2)} = ${ars.toFixed(2)}`;const reasons=decision==='ACT'?'The input looks like a familiar, high-quality sample. Confidence and familiarity are strong, while uncertainty is low. The action clears the safety threshold.':decision==='REVIEW'?'The model sees a plausible pattern, but familiarity or uncertainty leaves too little margin for automatic action. A human should verify the prediction.':'This input is outside the model comfort zone. Low confidence, unfamiliarity, or poor quality makes an automatic action unsafe, so KYA stops and asks for human review.';$('explanation-text').textContent=reasons;$('review-title').textContent=decision==='ACT'?'No intervention needed':'Human verification recommended';$('review-copy').textContent=decision==='ACT'?'High-readiness predictions can proceed automatically. Lower-scoring inputs are routed here for a human decision.':`This ${decision.toLowerCase()} case is held until a reviewer confirms the model prediction and risk context.`;$('run-id').textContent=`RUN #KYA-${String(Math.floor(Math.random()*900)+100)}`;showToast('Input analyzed successfully')}
document.querySelectorAll('[data-scroll]').forEach(button=>button.addEventListener('click',()=>$(button.dataset.scroll).scrollIntoView({behavior:'smooth'})));
document.querySelectorAll('.sample-button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.sample-button').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');state.sample=button.dataset.sample;state.image=null;state.reviewed=false;$('image-input').value='';$('preview-wrap').classList.remove('hidden');$('drop-zone').style.display='none';drawSample(state.sample);analyze()}));
$('analyze-button').addEventListener('click',analyze);
$('review-button').addEventListener('click',()=>{const decision=$('decision-title').textContent;if(decision==='ACT'){showToast('No cases currently need review');return}if(!state.reviewed){state.queue+=1;state.reviewed=true;$('queue-count').textContent=`${String(state.queue).padStart(2,'0')} IN QUEUE`}$('review-button').innerHTML='Queued for human review <i data-lucide="check"></i>';if(window.lucide)lucide.createIcons();showToast(`${decision} case added to review queue`)});
$('remove-image').addEventListener('click',()=>{$('preview-wrap').classList.add('hidden');$('drop-zone').style.display='flex';$('image-input').value='';state.image=null;state.sample='digit'});
const zone=$('drop-zone');['dragenter','dragover'].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.add('dragover')}));['dragleave','drop'].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.remove('dragover')}));zone.addEventListener('drop',event=>handleFile(event.dataTransfer.files[0]));$('image-input').addEventListener('change',event=>handleFile(event.target.files[0]));
function handleFile(file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){showToast('Please choose a PNG, JPG, or WEBP image');return}if(file.size>10*1024*1024){showToast('Image must be smaller than 10 MB');return}const reader=new FileReader();reader.onload=event=>{const image=new Image();image.onload=()=>{const canvas=$('preview-canvas'),ctx=canvas.getContext('2d'),scale=Math.min(440/image.width,260/image.height),width=image.width*scale,height=image.height*scale;ctx.clearRect(0,0,440,260);ctx.fillStyle='#e5eadf';ctx.fillRect(0,0,440,260);ctx.drawImage(image,(440-width)/2,(260-height)/2,width,height);const pixels=ctx.getImageData(0,0,440,260).data;let total=0,variance=0,edges=0,previous=0;for(let i=0;i<pixels.length;i+=4){const value=(pixels[i]+pixels[i+1]+pixels[i+2])/3;total+=value;variance+=value*value;if(i>4&&Math.abs(value-previous)>55)edges++;previous=value}const count=pixels.length/4,mean=total/count,spread=Math.sqrt(Math.max(0,variance/count-mean*mean)),quality=clamp(.45+spread/180),familiarity=clamp(.2+quality*.68),uncertainty=clamp(.85-quality*.7),confidence=clamp(.38+quality*.58-uncertainty*.18);state.sample='object';state.image=file.name;state.reviewed=false;samples.object={prediction:'Visual pattern',confidence,familiarity,uncertainty,quality,risk:clamp(edges/count*8)};document.querySelectorAll('.sample-button').forEach(item=>item.classList.remove('selected'));$('preview-wrap').classList.remove('hidden');zone.style.display='none';analyze()};image.onerror=()=>showToast('That image could not be read');image.src=event.target.result};reader.onerror=()=>showToast('Could not read the selected file');reader.readAsDataURL(file)}
